"""The append-only substrate — Invariants I2 and I3.

Two-tier storage:
    vault/substrate.db       SQLite (events, FTS5, interpretations)
    vault/objects/<aa>/<...> filesystem object store (binary + large text)

Public API surface — stable for the lifetime of the project. New helpers
may be added; existing signatures should not change without an explicit
constitutional review.
"""

from __future__ import annotations

from . import pipeline_events
from .checkpoint import start_checkpoint_loop
from .corrections import (
    CorrectionOutcome,
    PendingCorrection,
    decide_correction,
    read_pending_corrections,
)
from .db import init_db, open_db
from .entities import (
    EdgeInvalidation,
    EdgeReview,
    Entity,
    EntityEdge,
    EntityKindAssignment,
    EntityMention,
    EntityMerge,
    assign_entity_kind,
    entity_id,
    entity_id_v2,
    find_edges_for_source_event,
    find_entity_by_name,
    find_live_merge_from,
    iter_edges_for_entity,
    iter_mentions_for_event,
    latest_edge_review,
    latest_edge_reviews_batch,
    next_disambiguator,
    read_edge_invalidations,
    read_edges_by_source_event_ids,
    read_entities_batch,
    read_entity_by_id,
    read_mentions_batch,
    record_edge_review,
    resolve_canonical,
    resolve_canonical_batch,
    resolve_entity_kind,
    resolve_entity_kind_batch,
    retract_entity,
    retracted_entity_ids,
    retype_entity,
    write_edge_invalidation,
    write_entity,
    write_entity_edge,
    write_entity_mention,
    write_entity_merge,
    write_merge_invalidation,
)
from .events import (
    Event,
    iter_events,
    read_event_by_hash,
    read_event_by_id,
    write_event,
    write_event_with_status,
)
from .kinds import (
    BOOTSTRAP_KIND_SLUGS,
    KindRow,
    live_kind_slugs,
    live_kinds,
    resolve_kind_batch,
    resolve_kind_slug,
    resolve_to_live_kind,
    seed_bootstrap_kinds,
    write_kind_observation,
)
from .objects import (
    StreamingObjectWriter,
    object_exists,
    object_path,
    object_plaintext_size,
    object_size,
    read_object,
    write_object,
)
from .payload import (
    build_binary_payload,
    build_blob_ref_payload,
    build_compound_payload,
    build_text_payload,
    canonical_json,
    content_hash,
    derive_searchable_text,
)
from .schema import SCHEMA_VERSION
from .search import hybrid_search, rrf_merge, search_fts, search_vec
from .temporal import (
    TEMPORAL_CLASSES,
    EventTemporal,
    next_occurrence,
    next_relevant_moment,
    read_event_temporal,
    read_event_temporal_batch,
    temporal_relevance,
    upcoming_temporal,
    write_event_temporal,
)

__all__ = [
    "BOOTSTRAP_KIND_SLUGS",
    "SCHEMA_VERSION",
    "TEMPORAL_CLASSES",
    "CorrectionOutcome",
    "EdgeInvalidation",
    "EdgeReview",
    "Entity",
    "EntityEdge",
    "EntityKindAssignment",
    "EntityMention",
    "EntityMerge",
    "Event",
    "EventTemporal",
    "KindRow",
    "PendingCorrection",
    "StreamingObjectWriter",
    "assign_entity_kind",
    "build_binary_payload",
    "build_blob_ref_payload",
    "build_compound_payload",
    "build_text_payload",
    "canonical_json",
    "content_hash",
    "decide_correction",
    "derive_searchable_text",
    "entity_id",
    "entity_id_v2",
    "find_edges_for_source_event",
    "find_entity_by_name",
    "find_live_merge_from",
    "hybrid_search",
    "init_db",
    "iter_edges_for_entity",
    "iter_events",
    "iter_mentions_for_event",
    "latest_edge_review",
    "latest_edge_reviews_batch",
    "live_kind_slugs",
    "live_kinds",
    "next_disambiguator",
    "next_occurrence",
    "next_relevant_moment",
    "object_exists",
    "object_path",
    "object_plaintext_size",
    "object_size",
    "open_db",
    "pipeline_events",
    "read_edge_invalidations",
    "read_edges_by_source_event_ids",
    "read_entities_batch",
    "read_entity_by_id",
    "read_event_by_hash",
    "read_event_by_id",
    "read_event_temporal",
    "read_event_temporal_batch",
    "read_mentions_batch",
    "read_object",
    "read_pending_corrections",
    "record_edge_review",
    "resolve_canonical",
    "resolve_canonical_batch",
    "resolve_entity_kind",
    "resolve_entity_kind_batch",
    "resolve_kind_batch",
    "resolve_kind_slug",
    "resolve_to_live_kind",
    "retract_entity",
    "retracted_entity_ids",
    "retype_entity",
    "rrf_merge",
    "search_fts",
    "search_vec",
    "seed_bootstrap_kinds",
    "start_checkpoint_loop",
    "temporal_relevance",
    "upcoming_temporal",
    "write_edge_invalidation",
    "write_entity",
    "write_entity_edge",
    "write_entity_mention",
    "write_entity_merge",
    "write_event",
    "write_event_temporal",
    "write_event_with_status",
    "write_kind_observation",
    "write_merge_invalidation",
    "write_object",
]
